export {
  defaultStoragePath,
  hubUserRoot,
  legacyLedgerPath,
  migrateLegacyLedger,
  gatewayFromPage,
  gatewayFromProvider,
  processSpaceManager,
  setProcessSpaceManager,
  SpaceEventBus,
  SpaceGuardError,
  TaskSpaceManager,
  SPACE_STORAGE_VERSION,
} from './task-space-manager.ts'
export type {
  SpaceEvent,
  SpaceEventListener,
  SpaceEventType,
  SpaceWindowTabInfo,
  SpaceWindowTabs,
  UnmanagedTabInfo,
  OpenTabResult,
  SpaceGuardErrorCode,
  SpaceIdentity,
  SpaceInfo,
  SpaceOwnership,
  SpaceRecord,
  SpaceTabGateway,
  SpaceTabInfo,
  TabLike,
  TabRef,
  TabUrlReuseMode,
  TaskSpaceManagerOptions,
  TaskSpaceReapOptions,
  ReapEviction,
} from './task-space-manager.ts'
